### ISSUE TITLE
handle contexts inside conditions

### ISSUE THREAD

**Issue by Crocmagnon** [Crocmagnon/fatcontext#14]
Looks like this use case isn't detected:
```go
for {
	err := doSomething()
	if err != nil {
		ctx = context.WithValue(ctx, "key", "value")

		continue
	}

	doSomethingElse()
}
```

TODO:

- [x] confirm with a test case
- [ ] fix

**Comment by Crocmagnon** [comment]
There's a PR with a failing test case, if someone is interested in cracking this they're welcome :)

**Comment by venkycode** [comment]
taking this up
